"use client";

import { ArrowDownUp, Check, ChevronDown } from "lucide-react";
import { useEffect, useId, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { AUTHOR_ARCHIVE_SORT_OPTIONS, type AuthorArchiveSort } from "@/lib/reference/author-archive-search";
import { cn } from "@/lib/utils";

export default function AuthorArchiveSortMenu({ value, onChange }: { value: AuthorArchiveSort; onChange: (value: AuthorArchiveSort) => void }) {
  const [open, setOpen] = useState(false); const trigger = useRef<HTMLButtonElement>(null); const menu = useRef<HTMLDivElement>(null); const id = useId();
  const active = AUTHOR_ARCHIVE_SORT_OPTIONS.find((item) => item.value === value) ?? AUTHOR_ARCHIVE_SORT_OPTIONS[0];
  useEffect(() => { if (!open) return; const pointer = (event: PointerEvent) => { const target = event.target as Node; if (!trigger.current?.contains(target) && !menu.current?.contains(target)) setOpen(false); }; const key = (event: KeyboardEvent) => { if (event.key === "Escape") { setOpen(false); trigger.current?.focus(); } }; document.addEventListener("pointerdown", pointer); document.addEventListener("keydown", key); return () => { document.removeEventListener("pointerdown", pointer); document.removeEventListener("keydown", key); }; }, [open]);
  return <div className="relative shrink-0"><Button ref={trigger} type="button" variant="ghost" aria-label={`مرتب‌سازی نویسنده‌ها: ${active.label}`} aria-expanded={open} aria-controls={id} aria-haspopup="listbox" onClick={() => setOpen((current) => !current)} className="h-12 gap-1.5 rounded-[1rem] border border-border bg-card px-3 text-foreground shadow-[0_2px_8px_-5px_rgba(0,0,0,0.18)] hover:border-primary/40 hover:bg-primary/[0.06] hover:text-primary sm:h-[50px]"><ArrowDownUp className="h-[18px] w-[18px]" /><span className="hidden max-w-28 truncate text-xs font-black sm:inline">{active.label}</span><ChevronDown className={cn("hidden h-3.5 w-3.5 transition-transform sm:block", open && "rotate-180")} /></Button>{open ? <div id={id} ref={menu} role="listbox" aria-label="مرتب‌سازی نویسنده‌ها" className="absolute left-0 top-[calc(100%+0.5rem)] z-50 w-56 rounded-[1.1rem] border border-border bg-card p-1.5 text-right shadow-[0_20px_55px_-30px_rgba(0,0,0,0.48)]"><p className="px-2.5 pb-1.5 pt-1 text-[11px] font-bold text-muted-foreground">مرتب‌سازی بر اساس</p>{AUTHOR_ARCHIVE_SORT_OPTIONS.map((option) => { const selected = option.value === value; return <button key={option.value} type="button" role="option" aria-selected={selected} onClick={() => { onChange(option.value); setOpen(false); }} className={cn("flex w-full items-center justify-between gap-3 rounded-xl px-2.5 py-2 text-right text-xs font-bold transition", selected ? "bg-primary/10 text-primary" : "text-foreground hover:bg-muted")}>{option.label}{selected ? <Check className="h-3.5 w-3.5 shrink-0" /> : null}</button>; })}</div> : null}</div>;
}
