"use client";

import { useCallback, useEffect, useState } from "react";
import { ExternalLink, RefreshCw } from "lucide-react";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import { AdminActionButton, AdminDataTable, AdminDataTableActions, AdminDataTableCell, AdminDataTablePagination, AdminDataTableRow, AdminDataTableSearch } from "@/components/admin/AdminDataTable";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { apiFetch, confidenceLabels, DiscoveryBadge, itemStatusLabels, Score, sourceTypeLabels } from "./IranKetabDiscoveryUi";

type Source = { id: string; name: string };
type Membership = { discoverySourceId: string; sourceName: string; sourceType: string; sourcePosition: number | null };
type Candidate = { id: string; titleHint: string | null; authorHint: string | null; priorityScore: number; scoreBreakdown: { sourceScore?: number; multiSourceBonus?: number; positionBonus?: number; reasons?: string[] } | null; importConfidence: string; status: string; memberships: Membership[]; sources: Source[] };
const statuses = ["DISCOVERED", "SCORED", "QUEUED", "IMPORTING", "IMPORTED", "NEEDS_REVIEW", "SKIPPED", "FAILED"];

export default function IranKetabDiscoveryCandidatesClient() {
  const [items, setItems] = useState<Candidate[]>([]); const [sources, setSources] = useState<Source[]>([]);
  const [page, setPage] = useState(1); const [totalPages, setTotalPages] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [filters, setFilters] = useState({ q: "", status: "ALL", importConfidence: "ALL", minimumPriorityScore: "0", sourceId: "" });
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: String(page), q: filters.q, status: filters.status, importConfidence: filters.importConfidence, minimumPriorityScore: filters.minimumPriorityScore }); if (filters.sourceId) params.set("sourceId", filters.sourceId); const data = await apiFetch<{ items: Candidate[]; totalPages: number }>(`/api/admin/iranketab-discovery/items?${params}`); setItems(data.items); setTotalPages(data.totalPages); } catch (cause) { setError(cause instanceof Error ? cause.message : "بارگذاری نامزدها ناموفق بود"); } finally { setLoading(false); } }, [filters, page]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { void apiFetch<{ sources: Source[] }>("/api/admin/iranketab-discovery/sources?page=1").then((data) => setSources(data.sources)).catch(() => undefined); }, []);
  function updateFilter(key: keyof typeof filters, value: string) { setPage(1); setFilters((current) => ({ ...current, [key]: value })); }
  return <div className="space-y-6"><AdminPageHeader title="نامزدهای کشف ایران‌کتاب" description="کتاب‌های کشف‌شده را بر اساس شواهد منبع و امتیاز اولویت بررسی کنید." />
    {error ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p> : null}
    <div className="grid gap-3 rounded-[1.5rem] border border-border/70 bg-card/40 p-4 sm:grid-cols-2 lg:grid-cols-5"><AdminDataTableSearch value={filters.q} onChange={(value) => updateFilter("q", value)} placeholder="جست‌وجوی عنوان" /><Filter label="وضعیت" value={filters.status} onChange={(value) => updateFilter("status", value)}><option value="ALL">همه وضعیت‌ها</option>{statuses.map((value) => <option key={value} value={value}>{itemStatusLabels[value]}</option>)}</Filter><Filter label="اطمینان" value={filters.importConfidence} onChange={(value) => updateFilter("importConfidence", value)}><option value="ALL">همه سطح‌ها</option>{Object.entries(confidenceLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Filter><label className="grid gap-1 text-xs font-bold text-muted-foreground">حداقل امتیاز<Input type="number" min="0" max="100" value={filters.minimumPriorityScore} onChange={(e) => updateFilter("minimumPriorityScore", e.target.value)} /></label><Filter label="منبع" value={filters.sourceId} onChange={(value) => updateFilter("sourceId", value)}><option value="">همه منابع</option>{sources.map((source) => <option key={source.id} value={source.id}>{source.name}</option>)}</Filter></div>
    <div className="flex justify-end"><Button variant="outline" onClick={() => void load()} disabled={loading}><RefreshCw className="h-4 w-4" />به‌روزرسانی</Button></div>
    <AdminDataTable loading={loading} isEmpty={!items.length} emptyText="نامزدی با این فیلترها پیدا نشد" minWidth={1040} columns={[{ key: "book", label: "کتاب", align: "start" }, { key: "score", label: "امتیاز" }, { key: "breakdown", label: "چرایی امتیاز", align: "start" }, { key: "sources", label: "منابع", align: "start" }, { key: "status", label: "وضعیت" }, { key: "actions", label: "جزئیات" }]} footer={<AdminDataTablePagination page={page} totalPages={totalPages} onPageChange={setPage} />}>
      {items.map((item) => <AdminDataTableRow key={item.id}><AdminDataTableCell align="start"><p className="font-bold">{item.titleHint ?? "عنوان نامشخص"}</p><p className="mt-1 text-xs text-muted-foreground">{item.authorHint ?? "نویسنده نامشخص"}</p></AdminDataTableCell><AdminDataTableCell><Score value={item.priorityScore} /><div className="mt-2"><DiscoveryBadge value={item.importConfidence} label={`اطمینان ${confidenceLabels[item.importConfidence] ?? item.importConfidence}`} /></div></AdminDataTableCell><AdminDataTableCell align="start"><ScoreReasons breakdown={item.scoreBreakdown} /></AdminDataTableCell><AdminDataTableCell align="start"><div className="flex max-w-56 flex-wrap gap-1">{item.memberships.map((membership) => <span key={membership.discoverySourceId} title={sourceTypeLabels[membership.sourceType]} className="rounded-full border border-border/70 bg-background/50 px-2 py-1 text-[11px] font-bold">{membership.sourceName}{membership.sourcePosition ? ` · ${membership.sourcePosition.toLocaleString("fa-IR")}` : ""}</span>)}</div></AdminDataTableCell><AdminDataTableCell><DiscoveryBadge value={item.status} label={itemStatusLabels[item.status] ?? item.status} /></AdminDataTableCell><AdminDataTableCell><AdminDataTableActions><AdminActionButton href={`/admin/iranketab-discovery/items/${item.id}`} icon={<ExternalLink className="h-4 w-4" />} title="مشاهده و بررسی" /></AdminDataTableActions></AdminDataTableCell></AdminDataTableRow>)}
    </AdminDataTable>
  </div>;
}

function Filter({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label className="grid gap-1 text-xs font-bold text-muted-foreground">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="h-10 rounded-md border bg-background px-3 text-sm font-medium text-foreground">{children}</select></label>; }
function ScoreReasons({ breakdown }: { breakdown: Candidate["scoreBreakdown"] }) { if (!breakdown) return <span className="text-xs text-muted-foreground">هنوز محاسبه نشده</span>; const summary = [breakdown.sourceScore ? `منبع ${breakdown.sourceScore}` : null, breakdown.multiSourceBonus ? `چندمنبعی +${breakdown.multiSourceBonus}` : null, breakdown.positionBonus ? `رتبه +${breakdown.positionBonus}` : null].filter(Boolean); return <><p className="text-xs text-muted-foreground">{summary.join(" · ") || "جزئیات امتیاز"}</p>{breakdown.reasons?.[0] ? <p className="mt-1 line-clamp-2 text-[11px] text-muted-foreground">{breakdown.reasons[0]}</p> : null}</>; }
