"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, CircleSlash, ExternalLink, Loader2, MessageSquareWarning, Play } from "lucide-react";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiFetch, confidenceLabels, DiscoveryBadge, formatDate, itemStatusLabels, Score, sourceTypeLabels } from "./IranKetabDiscoveryUi";

type Membership = { id: string; discoverySourceId: string; sourceName: string; sourceType: string; sourceUrl: string; sourcePosition: number | null; firstSeenAt: string; lastSeenAt: string; sourceScoreContribution: number; sourceTitleHint: string | null; preferredEditionCode: string | null; metadata: Record<string, unknown> | null };
type Candidate = { id: string; iranKetabBookId: string; canonicalUrl: string; titleHint: string | null; authorHint: string | null; priorityScore: number; scoreBreakdown: { sourceScore?: number; multiSourceBonus?: number; positionBonus?: number; reasons?: string[] } | null; importConfidence: string; status: string; importSessionId: string | null; failureCode: string | null; failureReason: string | null; retryCount: number; nextRetryAt: string | null; existingCatalogMatch: { id: string; title: string | null; slug: string | null } | null; memberships: Membership[]; createdAt: string; updatedAt: string };

export default function IranKetabDiscoveryCandidateDetailClient({ id }: { id: string }) {
  const [item, setItem] = useState<Candidate | null>(null); const [loading, setLoading] = useState(true); const [working, setWorking] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { const data = await apiFetch<{ item: Candidate }>(`/api/admin/iranketab-discovery/items/${id}`); setItem(data.item); } catch (cause) { setError(cause instanceof Error ? cause.message : "بارگذاری نامزد ناموفق بود"); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function action(actionName: "IGNORE" | "NEEDS_REVIEW" | "APPROVE_FOR_IMPORT") { setWorking(actionName); setError(""); setNotice(""); try { const data = await apiFetch<{ message?: string }>(`/api/admin/iranketab-discovery/items/${id}`, { method: "PATCH", body: JSON.stringify({ action: actionName }) }); setNotice(data.message ?? "وضعیت نامزد به‌روزرسانی شد"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "تغییر وضعیت ناموفق بود"); } finally { setWorking(""); } }
  async function startImport() { setWorking("IMPORT"); setError(""); setNotice(""); try { const data = await apiFetch<{ message?: string; session: { id: string } }>(`/api/admin/iranketab-discovery/items/${id}/import`, { method: "POST" }); setNotice(data.message ?? "آماده‌سازی ورود شروع شد"); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "آماده‌سازی ورود ناموفق بود"); } finally { setWorking(""); } }
  if (loading) return <div className="flex min-h-48 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin text-primary" /></div>;
  if (!item) return <div className="space-y-4"><Button asChild variant="outline"><Link href="/admin/iranketab-discovery/items"><ArrowRight className="h-4 w-4" />بازگشت</Link></Button><p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-destructive">{error || "نامزد یافت نشد"}</p></div>;
  const canStartImport = item.status === "QUEUED" || item.status === "IMPORTING";
  return <div className="space-y-6"><AdminPageHeader title={item.titleHint ?? "کتاب کشف‌شده"} description={item.authorHint ?? "نویسنده نامشخص"} action={<Button asChild variant="outline"><Link href="/admin/iranketab-discovery/items"><ArrowRight className="h-4 w-4" />بازگشت به نامزدها</Link></Button>} />
    {error ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p> : null}{notice ? <p className="rounded-xl border border-primary/30 bg-primary/10 px-4 py-3 text-sm text-primary">{notice}</p> : null}
    <div className="grid gap-4 lg:grid-cols-3"><Card className="lg:col-span-2"><CardHeader><CardTitle className="flex flex-wrap items-center gap-2">وضعیت بررسی <DiscoveryBadge value={item.status} label={itemStatusLabels[item.status] ?? item.status} /><DiscoveryBadge value={item.importConfidence} label={`اطمینان ${confidenceLabels[item.importConfidence] ?? item.importConfidence}`} /></CardTitle></CardHeader><CardContent className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => void action("IGNORE")} disabled={Boolean(working)}><CircleSlash className="h-4 w-4" />نادیده گرفتن</Button><Button variant="outline" onClick={() => void action("NEEDS_REVIEW")} disabled={Boolean(working)}><MessageSquareWarning className="h-4 w-4" />نیازمند بررسی</Button><Button onClick={() => void action("APPROVE_FOR_IMPORT")} disabled={Boolean(working)}><CheckCircle2 className="h-4 w-4" />تأیید برای ورود</Button><Button variant="secondary" onClick={() => void startImport()} disabled={!canStartImport || Boolean(working)}><Play className="h-4 w-4" />شروع ورود</Button></CardContent></Card><Card><CardHeader><CardTitle>امتیاز اولویت</CardTitle></CardHeader><CardContent><p className="text-3xl"><Score value={item.priorityScore} /></p><p className="mt-2 text-xs text-muted-foreground">ایران‌کتاب: {item.iranKetabBookId}</p></CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>توضیح امتیاز</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><ScoreLine label="امتیاز منابع" value={item.scoreBreakdown?.sourceScore} /><ScoreLine label="امتیاز چندمنبعی" value={item.scoreBreakdown?.multiSourceBonus} /><ScoreLine label="امتیاز رتبه" value={item.scoreBreakdown?.positionBonus} /><ul className="list-disc space-y-1 pr-5 text-muted-foreground">{item.scoreBreakdown?.reasons?.map((reason) => <li key={reason}>{reason}</li>) ?? <li>توضیحی ثبت نشده است.</li>}</ul></CardContent></Card><Card><CardHeader><CardTitle>وضعیت ورود</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><p><span className="text-muted-foreground">نشست ورود:</span> {item.importSessionId ? <Link className="font-bold text-primary hover:underline" href={`/admin/books/import-history/${item.importSessionId}`}>{item.importSessionId}</Link> : "هنوز ایجاد نشده"}</p>{item.failureCode ? <p className="text-destructive">{item.failureCode}: {item.failureReason}</p> : null}<p className="text-muted-foreground">تلاش مجدد: {item.retryCount.toLocaleString("fa-IR")}</p><a href={item.canonicalUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-bold text-primary hover:underline"><ExternalLink className="h-4 w-4" />صفحه ایران‌کتاب</a></CardContent></Card></div>
    <div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><CardTitle>ارتباط با کاتالوگ</CardTitle></CardHeader><CardContent>{item.existingCatalogMatch ? <Link className="font-bold text-primary hover:underline" href={`/admin/books/${item.existingCatalogMatch.id}/edit`}>{item.existingCatalogMatch.title ?? "کتاب کاتالوگ"}</Link> : <p className="text-sm text-muted-foreground">تطابقی با کاتالوگ ثبت نشده است.</p>}</CardContent></Card><Card><CardHeader><CardTitle>تاریخچه نامزد</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-muted-foreground"><p>اولین ثبت: {formatDate(item.createdAt)}</p><p>آخرین تغییر: {formatDate(item.updatedAt)}</p><p>آخرین زمان تلاش: {formatDate(item.nextRetryAt)}</p></CardContent></Card></div>
    <Card><CardHeader><CardTitle>منابع و عضویت‌ها</CardTitle></CardHeader><CardContent className="space-y-3">{item.memberships.map((membership) => <div key={membership.id} className="rounded-xl border border-border/70 bg-muted/20 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="font-bold">{membership.sourceName} <span className="mr-2 text-xs font-medium text-muted-foreground">{sourceTypeLabels[membership.sourceType] ?? membership.sourceType}</span></p><p className="mt-1 text-xs text-muted-foreground">اولین مشاهده: {formatDate(membership.firstSeenAt)} · آخرین مشاهده: {formatDate(membership.lastSeenAt)}</p></div><div className="text-left text-sm"><p>سهم امتیاز: <b>{membership.sourceScoreContribution.toLocaleString("fa-IR")}</b></p><p className="mt-1 text-muted-foreground">رتبه: {membership.sourcePosition?.toLocaleString("fa-IR") ?? "—"}</p></div></div>{membership.sourceTitleHint ? <p className="mt-2 text-xs text-muted-foreground">عنوان در منبع: {membership.sourceTitleHint}</p> : null}</div>)}</CardContent></Card>
  </div>;
}

function ScoreLine({ label, value }: { label: string; value: number | undefined }) { return <div className="flex items-center justify-between"><span className="text-muted-foreground">{label}</span><b>{(value ?? 0).toLocaleString("fa-IR")}</b></div>; }
