"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Activity, BadgeCheck, BookOpenCheck, CircleAlert, Database, ListChecks, RefreshCw, TimerReset } from "lucide-react";
import AdminPageHeader from "@/components/admin/AdminPageHeader";
import AdminStatCard from "@/components/admin/AdminStatCard";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { apiFetch, confidenceLabels, crawlStatusLabels, DiscoveryBadge, formatDate, itemStatusLabels, Score } from "./IranKetabDiscoveryUi";

type Snapshot = {
  overview: { enabledSources: number; sourcesExecutedRecently: number; totalCandidates: number; averagePriorityScore: number; queuedImportJobs: number; failedImportJobs: number; candidatesByStatus: Record<string, number>; candidatesByConfidence: Record<string, number> };
  sourcePerformance: Array<{ id: string; name: string; lastCrawledAt: string | null; discoveredBookCount: number; booksQueued: number; failures: number; successRate: number; crawlStatus: string }>;
  recentActivity: { latestRuns: Array<{ id: string; status: string; startedAt: string; booksFound: number; errorMessage: string | null; sourceId: string; sourceName: string }>; latestDiscoveredBooks: Array<{ id: string; titleHint: string | null; authorHint: string | null; priorityScore: number; importConfidence: string; status: string; createdAt: string }>; latestFailedImports: Array<{ id: string; discoveryItemId: string; lastErrorCode: string | null; lastErrorMessage: string | null; completedAt: string | null; titleHint: string | null }> };
};

export default function IranKetabDiscoveryDashboardClient() {
  const [data, setData] = useState<Snapshot | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const load = useCallback(async () => { setLoading(true); setError(""); try { setData(await apiFetch<Snapshot>("/api/admin/iranketab-discovery/analytics")); } catch (cause) { setError(cause instanceof Error ? cause.message : "بارگذاری تحلیل‌ها ناموفق بود"); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <div className="flex min-h-64 items-center justify-center"><Activity className="h-6 w-6 animate-pulse text-primary" /></div>;
  if (!data) return <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-4 text-destructive">{error || "تحلیل‌ها در دسترس نیستند"}</p>;
  const { overview, sourcePerformance, recentActivity } = data;
  return <div className="space-y-7"><AdminPageHeader title="داشبورد کشف ایران‌کتاب" description="سلامت منابع، کیفیت نامزدها و وضعیت آماده‌سازی ورود." action={<Button variant="outline" onClick={() => void load()}><RefreshCw className="h-4 w-4" />به‌روزرسانی</Button>} />
    {error ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</p> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><AdminStatCard label="منابع فعال" value={overview.enabledSources} icon={Database} href="/admin/iranketab-discovery/sources" /><AdminStatCard label="اجرای ۲۴ ساعت اخیر" value={overview.sourcesExecutedRecently} icon={TimerReset} /><AdminStatCard label="کل نامزدها" value={overview.totalCandidates} icon={BookOpenCheck} href="/admin/iranketab-discovery/items" /><AdminStatCard label="میانگین اولویت" value={overview.averagePriorityScore.toLocaleString("fa-IR")} icon={BadgeCheck} tone="primary" /><AdminStatCard label="کارهای صف ورود" value={overview.queuedImportJobs} icon={ListChecks} href="/admin/iranketab-discovery/jobs" tone="primary" /><AdminStatCard label="خطاهای صف ورود" value={overview.failedImportJobs} icon={CircleAlert} href="/admin/iranketab-discovery/jobs?status=FAILED" tone="warning" /></section>
    <section className="grid gap-4 lg:grid-cols-2"><Distribution title="نامزدها بر اساس وضعیت" items={overview.candidatesByStatus} labels={itemStatusLabels} /><Distribution title="نامزدها بر اساس اطمینان" items={overview.candidatesByConfidence} labels={confidenceLabels} /></section>
    <Card><CardHeader><CardTitle>عملکرد منابع</CardTitle></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[720px] text-sm"><thead className="border-b text-right text-xs text-muted-foreground"><tr><th className="pb-3">منبع</th><th className="pb-3">آخرین اجرا</th><th className="pb-3">کتاب‌های کشف‌شده</th><th className="pb-3">در صف</th><th className="pb-3">خطاها</th><th className="pb-3">نرخ موفقیت</th></tr></thead><tbody>{sourcePerformance.map((source) => <tr key={source.id} className="border-b last:border-0"><td className="py-3 font-bold">{source.name}<div className="mt-1"><DiscoveryBadge value={source.crawlStatus} label={crawlStatusLabels[source.crawlStatus] ?? source.crawlStatus} /></div></td><td className="py-3 text-muted-foreground">{formatDate(source.lastCrawledAt)}</td><td className="py-3">{source.discoveredBookCount.toLocaleString("fa-IR")}</td><td className="py-3">{source.booksQueued.toLocaleString("fa-IR")}</td><td className="py-3">{source.failures.toLocaleString("fa-IR")}</td><td className="py-3"><span className="font-black text-primary">{source.successRate.toLocaleString("fa-IR")}٪</span></td></tr>)}</tbody></table>{!sourcePerformance.length ? <p className="py-8 text-center text-sm text-muted-foreground">منبعی برای نمایش وجود ندارد.</p> : null}</CardContent></Card>
    <section className="grid gap-4 xl:grid-cols-3"><ActivityCard title="آخرین اجراهای کشف">{recentActivity.latestRuns.map((run) => <div key={run.id} className="rounded-xl border border-border/70 p-3"><div className="flex items-center justify-between gap-2"><b>{run.sourceName}</b><DiscoveryBadge value={run.status === "SUCCESS" ? "SUCCEEDED" : run.status} label={run.status === "SUCCESS" ? "موفق" : "ناموفق"} /></div><p className="mt-2 text-xs text-muted-foreground">{run.booksFound.toLocaleString("fa-IR")} کتاب · {formatDate(run.startedAt)}</p>{run.errorMessage ? <p className="mt-1 text-xs text-destructive">{run.errorMessage}</p> : null}</div>)}</ActivityCard><ActivityCard title="آخرین کتاب‌های کشف‌شده">{recentActivity.latestDiscoveredBooks.map((book) => <Link key={book.id} href={`/admin/iranketab-discovery/items/${book.id}`} className="block rounded-xl border border-border/70 p-3 transition-colors hover:border-primary/30"><b>{book.titleHint ?? "عنوان نامشخص"}</b><p className="mt-1 text-xs text-muted-foreground">{book.authorHint ?? "نویسنده نامشخص"}</p><div className="mt-2 flex items-center justify-between"><Score value={book.priorityScore} /><DiscoveryBadge value={book.importConfidence} label={confidenceLabels[book.importConfidence] ?? book.importConfidence} /></div></Link>)}</ActivityCard><ActivityCard title="آخرین خطاهای ورود">{recentActivity.latestFailedImports.map((job) => <Link key={job.id} href={`/admin/iranketab-discovery/items/${job.discoveryItemId}`} className="block rounded-xl border border-destructive/20 bg-destructive/5 p-3"><b>{job.titleHint ?? "کتاب نامشخص"}</b><p className="mt-1 text-xs text-destructive">{job.lastErrorMessage ?? job.lastErrorCode ?? "خطای نامشخص"}</p><p className="mt-1 text-[11px] text-muted-foreground">{formatDate(job.completedAt)}</p></Link>)}</ActivityCard></section>
  </div>;
}

function Distribution({ title, items, labels }: { title: string; items: Record<string, number>; labels: Record<string, string> }) { const total = Object.values(items).reduce((sum, value) => sum + value, 0); return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3">{Object.entries(items).map(([key, value]) => <div key={key}><div className="mb-1 flex justify-between text-sm"><span>{labels[key] ?? key}</span><b>{value.toLocaleString("fa-IR")}</b></div><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${total ? (value / total) * 100 : 0}%` }} /></div></div>)}{!total ? <p className="text-sm text-muted-foreground">داده‌ای ثبت نشده است.</p> : null}</CardContent></Card>; }
function ActivityCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="space-y-3">{children || <p className="text-sm text-muted-foreground">داده‌ای ثبت نشده است.</p>}</CardContent></Card>; }
