export const ADMIN_BOOK_STRING_LIMITS = {
  title: 500,
  originalTitle: 500,
  author: 300,
  genre: 2000,
  description: 10000,
  country: 200,
  language: 50,
  translator: 300,
  publisher: 300,
  isbn: 20,
  editionLabel: 200,
  externalLinkLabel: 120,
  externalLinkUrl: 2048,
} as const

export const ADMIN_BOOK_FIELD_LABELS: Record<string, string> = {
  title: "عنوان کتاب",
  originalTitle: "عنوان اصلی",
  author: "نویسنده",
  genre: "دسته‌بندی‌های کتاب",
  description: "توضیحات کتاب",
  country: "کشور",
  language: "زبان",
  translator: "مترجم",
  publisher: "ناشر",
  isbn: "شابک",
  editionLabel: "عنوان نسخه/چاپ",
  pageCount: "تعداد صفحات",
  publishedYear: "سال انتشار",
  coverImage: "تصویر جلد",
  status: "وضعیت",
  regenerateSlug: "بازتولید اسلاگ",
  externalLinks: "لینک‌های بیرونی",
  provider: "فروشگاه لینک",
  type: "نوع لینک",
  url: "آدرس لینک",
  label: "برچسب لینک",
  isActive: "وضعیت لینک",
  sortOrder: "ترتیب لینک",
}
